name: 'Project "Piper"'
description: 'CI/CD tooling for the SAP Ecosystem'
inputs:
  version:
    description: 'version of project "Piper" binary to run'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - run: |
        java -version
        mvn -v
        cat /etc/os-release
      shell: bash

    - run: |
        echo Installing Project "Piper" version ${{ inputs.version }}
        wget https://github.com/SAP/jenkins-library/releases/latest/download/piper_master
        sudo mv piper_master /usr/local/bin/piper
      shell: bash

    - run: /usr/local/bin/piper mavenBuild
      shell: bash

    - run: /usr/local/bin/piper mavenExecuteIntegration
      shell: bash

    - run: /usr/local/bin/piper mavenExecuteStaticCodeChecks
      shell: bash

